cert: vault:arcalos-staging-mgmt/lighthouse-githubapp/cloudbees-cicd-staging:private-key
id: vault:arcalos-staging-mgmt/lighthouse-githubapp/cloudbees-cicd-staging:app-id
secret: vault:arcalos-staging-mgmt/lighthouse-githubapp/cloudbees-cicd-staging:webhook-secret

tenantService:
  url: http://jx-tenant-service

replicaCount: 3

debug: true

env:
  BOT_NAME: arcalos-staging[bot]
