{{- $prefix := regexFind "^[^.]+." .Values.cluster.ingress.domain }}
{{- $rootDomain := trimPrefix $prefix .Values.cluster.ingress.domain }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jxui
spec:
  rules:
  # This domain MUST be first as the oauth proxy uses the first domain in the list to work out it's redirect url
  - host: dashboard.{{ $rootDomain }}
    http:
      paths:
        - backend:
            serviceName: oauth-proxy-jxui-backend
            servicePort: 80
          path: /api
{{- if .Values.cluster.ingress.tls.enabled }}
  tls:
  - hosts:
      - dashboard.{{ $rootDomain }}
{{- if .Values.cluster.ingress.tls.production }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
