apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: lighthouse-githubapp
spec:
  rules:
  - host: lighthouse-githubapp{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: lighthouse-githubapp
          servicePort: 80
{{- if .Values.cluster.ingress.tls.enabled }}
  tls:
  - hosts:
    - lighthouse-githubapp{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
{{- if .Values.cluster.ingress.tls.production }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
