apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-secret: kuberhealthy-basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
  name: kuberhealthy
spec:
  rules:
  - host: kuberhealthy{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: kuberhealthy
          servicePort: 80
{{- if .Values.cluster.ingress.tls.enabled }}
  tls:
  - hosts:
    - kuberhealthy{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
{{- if .Values.cluster.ingress.tls.production }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
