apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: boot-tenant-service
spec:
  rules:
  - host: boot-tenant-service{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: jx-tenant-service
          servicePort: 80
        path: /api/v1/(domain|nameservers|version|repositories|git/tokens|workspaces/token/tmp|test/workspaces|hmac|workspace).*$
{{- if .Values.cluster.ingress.tls.enabled }}
  tls:
  - hosts:
    - boot-tenant-service{{ .Values.cluster.ingress.namespaceSubDomain }}{{ .Values.cluster.ingress.domain }}
{{- if .Values.cluster.ingress.tls.production }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.cluster.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
