{{- $prefix := regexFind "^[^.]+." .Requirements.ingress.domain }}
{{- $rootDomain := trimPrefix $prefix .Requirements.ingress.domain }}
jxui:
  gcpSA: vault:arcalos-staging-mgmt/aps-alpha/arcalos-prod-sa:json
  replicaCount: 2
  skipExposeService: true
  sso:
    create: true
    useSSOOperator: false
    connector: arcalos
    signOutURL: /oauth2/sign_out?rd=https%3A%2F%2Fid.beescloud.com%2Fv2%2Flogout
  roxApiKey: vault:arcalos-staging-mgmt/feature-flag/rox:api-key
  segmentWriteKey: vault:arcalos-staging-mgmt/monitoring/segment:write-key
  service:
    serviceAnnotations:
      fabric8.io/expose: "false"
      fabric8.io/exposeUrl: https://arcalosui{{ .Requirements.ingress.namespaceSubDomain }}{{ $rootDomain }}
    backend:
      initGcpServiceAccount: true
