adminUser:
  password: vault:arcalos-staging-mgmt/adminUser:password
  username: admin
dashboardAuthID: vault:arcalos-staging-mgmt/dashboard/auth:id
dashboardAuthSecret: vault:arcalos-staging-mgmt/dashboard/auth:secret
enableDocker: false
pipelineUser:
  email: operations+arcalos-admin-bot@googlegroups.com
  token: vault:arcalos-staging-mgmt/pipelineUser:token
  username: arcalos-admin-bot
prow:
  hmacToken: vault:arcalos-staging-mgmt/prow:hmacToken

parentDNSZone: staging-jxaas-live-parent
parentDomain: staging-jxaas.live
parentProject: staging-arcalos-domain-name
tenantFolderID: "610016331961"
tenantServiceBasicAuth: vault:arcalos-staging-mgmt/jx-tenant-service/basic-auth:password
