gitops:
  owner: {{ .Requirements.cluster.environmentGitOwner }}

tekton:
{{- if eq .Requirements.webhook "prow" }}
  enabled: true
{{- else if eq .Requirements.webhook "lighthouse" }}
  enabled: true
{{- else }}
  enabled: false
{{- end }}

{{- if eq .Requirements.cluster.provider "openshift" }}
  rbac:
    cluster: false
  cluster:
    crds:
      create: false
    resources:
      create: false
{{- end }}

{{- if eq .Requirements.cluster.provider "openshift" }}
jenkins-x-platform:
  gcpreviews:
    clusterrole:
      enabled: false

  gcactivities:
    clusterrole:
      enabled: false

  gcpods:
    clusterrole:
      enabled: false

  postinstalljob:
    clusterrole:
      enabled: false

  controllerworkflow:
    clusterrole:
      enabled: false

  controllerbuild:
    clusterrole:
      enabled: false

  controllercommitstatus:
    clusterrole:
      enabled: false

  controllerrole:
    clusterrole:
      enabled: false

  controllerteam:
    clusterrole:
      enabled: false

  heapster:
    enabled: false
    rbac:
      create: false
{{- end }}

arcalosAlpha:
  pipelineGithubUser: vault:arcalos-staging-mgmt/aps-alpha/arcalos:pipeline-github-user
  pipelineGithubToken: vault:arcalos-staging-mgmt/aps-alpha/arcalos:pipeline-github-token
  pipelineGithubEmail: vault:arcalos-staging-mgmt/aps-alpha/arcalos:pipeline-github-email
  gitOwner: vault:arcalos-staging-mgmt/aps-alpha/arcalos:git-owner
  ciSA: vault:arcalos-staging-mgmt/aps-alpha/arcalos-prod-sa:json
  segmentWriteKey: vault:arcalos-staging-mgmt/monitoring/segment:write-key
  runBootSchedule: "0 * * * *"
  domainIssuerPassword: vault:arcalos-staging-mgmt/aps-alpha/arcalos:domain-issuer-password # pragma: allowlist secret
  domainIssuerUsername: vault:arcalos-staging-mgmt/aps-alpha/arcalos:domain-issuer-username
  domainIssuerUrl: "https://jx-tenant-service{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}"
